version: "3.8"
services:
  dev:
    container_name: todo-app-dev
    build: .
    command: npm run dev
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/todolist
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    container_name: mongodb
    image: mongo:latest
    ports:
      - '27017:27017'

  prod:
    container_name: todo-app-prod
    build: .
    command: npm start
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
